version: "3.8"
services:
  db:
    container_name: "learn-db" 
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '${DB_HOST}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPY_PASSWORD: "1"
    healthcheck:
      test: ["CMD", "mysqladmin", "-u${DB_USERNAME}", "-p${DB_PASSWORD}", "ping"]
      retries: 3
      timeout: 5s
    networks:
      lean-server-net:
        ipv4_address: '${DB_HOST}'
  learn-server:
    container_name: "learn-server" 
    build: .
    ports: 
      - "${SERVER_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true

    networks:
      lean-server-net:
        ipv4_address: "${SERVER_HOST}"

networks:
  lean-server-net:
    driver: bridge
    ipam:
      config:
        - subnet: "${DOCKER_SUBNET}/16"
          gateway: "${DOCKER_GATEWAY}"
