version: "3.8"
services:
  db:
    container_name: "learn-db" 
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '${DB_HOST}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPY_PASSWORD: "1"
    healthcheck:
      test: ["CMD", "mysqladmin", "-u${DB_USERNAME}", "-p${DB_PASSWORD}", "ping"]
      retries: 3
      timeout: 5s
    networks:
      gruber-net:
        ipv4_address: '${DB_HOST}'
  learn-server:
    container_name: "learn-server" 
    build: .
    ports: 
      - "4000:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true

    networks:
      gruber-net:
        ipv4_address: 10.8.0.3

networks:
  gruber-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1
